Mishima/three.js(animation)
Shiba-Lab/shibafes2023-g pull request #12
Opened 2023-10-02 10:21 UTC by perl-0815

## 概要
gltfのアニメーションクリップをクローンしたモデルごとに変更できるようにしました。現在はランダムな時間に花が開くようになっています。

### やったこと
・util.tsにgenerateNumberクラスを設置しgetRandomNumber関数を作成しました。今後このクラスには何かの数値生成に関する関数を追記する予定です。(現在はflowerClusterのみに使用、index.tsでも使う予定)
・新たにgltfAnimation.tsにrandomizeAnimationStartFrame関数を作成その名前の通り、gltfモデルからクリップを取り出しアニメーションの開始フレームとその後に続くアニメーション全体をずらす関数です。現在の問題点としてモデル単体ではアニメーションクリップを編集することができなかったためシーン全体による変更を行なっています。重くなる可能性があるため修正すべきかもしれませんがこれ以外の方法が現在わかりません。
・あとgltfモデルをクローンすることで複数モデルを扱うことができるようにしてあります。アニメーションミキサーについても同様です。

### やらなかったこと(あれば)
・アニメーションのループの終端の処理(バグは発生しませんが動画の再生のようになり現在はあまり再利用できるものではありません)
・花の集団そのものの複製とそれぞれのアニメーションの処理
・マテリアルの設定

## スクリーンショット

![Image 2023-10-02 at 19 19](https://github.com/Shiba-Lab/shibafes2023-g/assets/134142294/9319a576-bf09-47e2-883e-f4cad73cffdc)

## 破壊的変更があるか(あれば内容を記載)

- [ ] YES
- [○] NO

## チェック項目

- [○] lintが通る
- [○] 複雑なコードにはコメントを記載してある

## 関連Issue

## レビュワーへのコメント
今までと比べ大幅な変更をしたのでご確認の程よろしくお願いします

2023-10-02 16:58 UTC, yudai1204 requested changes
確認お願いします 🙏

2023-10-02 16:58 UTC, yudai1204 commented on frontend-main/src/index.ts
>    const flowerClusterCoordinate: THREE.Vector3[] = flowerClusterTransform.getCoordinates();
ClassやObjectの中に入れてほしいです

2023-10-02 16:58 UTC, yudai1204 commented on frontend-main/src/index.ts
> +
使わないところは消すか、別のファイルにexport constとかでまとめてほしいです

2023-10-02 23:49 UTC, perl-0815 commented on frontend-main/src/util.ts
> +}
すごく見やすいです。ありがとうございます

2023-10-02 23:53 UTC, perl-0815 commented on frontend-main/src/util.ts
> +}
エラーがあって少し修正させていただいたので後ほどご確認をお願いします

2023-10-03 01:59 UTC, perl-0815 commented on frontend-main/src/index.ts
> +//import { generateNumber } from "./util";
消しました！

2023-10-03 02:00 UTC, perl-0815 commented on frontend-main/src/index.ts
>    const flowerClusterCoordinate: THREE.Vector3[] = flowerClusterTransform.getCoordinates();
変えてみました。合っているかわからないのでご確認をお願いします

2023-10-03 02:00 UTC, perl-0815 commented on frontend-main/src/index.ts
> +
消しました

2023-10-03 08:14 UTC, yudai1204 approved these changes
![LGTM](https://firebasestorage.googleapis.com/v0/b/lgtmgen.appspot.com/o/images%2F8f0923f7-5d5d-4083-a37f-80a3ddcff0c3.jpg?alt=media&token=e81f57aa-7f22-45fa-96b3-22944865c798)

2023-10-03 08:33 UTC, merged