任意の2色の間でグラデーションを作るマテリアルの作成
Shiba-Lab/shibafes2023-g pull request #23
Opened 2023-10-10 00:17 UTC by perl-0815

## 概要
createMaterial関数で任意の2色を入れると、その2色間でグラデーションとなるようなマテリアルを作成するように変更した。グラデーションの基準は法線のy軸成分で判断している。

### やったこと
createMaterialの引数に2つのTHREE.Color型を追加した。HLSLでそれを読み込みシェーダーを作った。

### やらなかったこと(あれば)
アルファチャンネルの有効化。不透明度の設定。

## スクリーンショット

## 破壊的変更があるか(あれば内容を記載)

- [ ] YES
- [○] NO

## チェック項目

- [○] lintが通る
- [○] 複雑なコードにはコメントを記載してある

## 関連Issue
不透明度のアニメーションを作る

## レビュワーへのコメント
ご確認よろしくお願いします。

2023-10-10 01:43 UTC, yudai1204 requested changes
コード自体は完璧そう！
ただ、1点だけ気になったところを確認お願いします！
理由があってそうしてるのであればそのまま再レビューで大丈夫です

2023-10-10 01:43 UTC, yudai1204 commented on frontend-main/src/material/createMaterial.ts
このあたり、別のHLSLファイルに分割して読み込んだ方がHLSLのシンタックスエラーとか整形とか効くんじゃないかな

https://zenn.dev/koudaiishigame/articles/022d4690dae13f

2023-10-10 04:16 UTC, perl-0815 commented on frontend-main/src/material/createMaterial.ts
こだわりはないので直します！

2023-10-25 14:02 UTC, perl-0815 commented
前回の修正のマージリクエストを忘れたまま新機能追加してしまいましたすみません……。
HLSL関係は変更していませんので前回のままです。

## 概要
グレースケールシェーダーを作成し、レンダリングパスの末端に繋げることでレンダリングされた画像をグレースケールに変換できるようにした

### やったこと
grayScaleAnimateを作成し、レンダリングの結果をグレースケールに変換できるようにした。レンダリングパスを作成し、レンダリング結果に対して後からさまざまな編集が行えるようにした。(現在はグレースケールのみ)
また、animate.tsにおいてRenderTargetが変更された場合にバグが発生しないよう、
renderer.setRenderTarget(null);の一行を追加した。


### やらなかったこと(あれば)
アルファチャンネルの有効化。不透明度の設定。(何回か試していますがかなり厳しそうです)

## スクリーンショット

![Image 2023-10-25 at 23 01](https://github.com/Shiba-Lab/shibafes2023-g/assets/134142294/e2e4b8a1-c83e-4016-9033-ba0d442d6064)

## 破壊的変更があるか(あれば内容を記載)

- [ ] YES
- [○] NO

## チェック項目

- [○] lintが通る
- [○] 複雑なコードにはコメントを記載してある

## 関連Issue
不透明度のアニメーションを作る

## レビュワーへのコメント
ご確認よろしくお願いします。

2023-10-26 14:47 UTC, yudai1204 approved these changes
良さそう
![LGTM](https://firebasestorage.googleapis.com/v0/b/lgtmgen.appspot.com/o/images%2F48a87e71-10eb-41ef-a4d2-ce5c25af1d5f.jpg?alt=media&token=ae3d8545-14f9-4e59-85f4-f9743a33fb71)

2023-10-26 17:11 UTC, merged